// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ajalck/spine/pkg/api"
	"github.com/ajalck/spine/pkg/api/handler"
	"github.com/ajalck/spine/pkg/repository"
	"github.com/ajalck/spine/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI() *api.Server {
	authRepo := repository.NewAuthRepo()
	authUseCase := usecase.NewAuthUseCase(authRepo)
	authHandler := handler.NewAuthHandler(authUseCase)
	server := api.NewServerHTTP(authHandler)
	return server
}
